-- creating initial table
CREATE TABLE flatmates(
	student1_id TEXT NOT NULL,
	student1_name TEXT,
	student1_min_budget INT,
	student1_max_budget INT,
	student1_uni TEXT,
	student1_course TEXT,
	student1_yrOfStudy INT,
	student1_age INT,
	student1_country TEXT,
	student1_property TEXT,
	student1_smoking TEXT,
	student1_petFriendly TEXT,
	student1_cleanliness TEXT,
	student1_noiseTolerance TEXT,
	student1_bio TEXT,
	student2_id TEXT NOT NULL,
	student2_name TEXT,
	student2_min_budget INT,
	student2_max_budget INT,
	student2_uni TEXT,
	student2_course TEXT,
	student2_yrOfStudy INT,
	student2_age INT,
	student2_country TEXT,
	student2_property TEXT,
	student2_smoking TEXT,
	student2_petFriendly TEXT,
	student2_cleanliness TEXT,
	student2_noiseTolerance TEXT,
	student2_bio TEXT,
	compatibility_score INT
)